sudo: required

language: python 

python: 
  - "2.7"

services:
  - docker

before_install:
  - cd docker/python2
  - docker build -t sonata .
  - docker run sonata /bin/bash -c "python versioninfo.py"

script:
  - pwd
  - ls -alt
  - docker images
